import Web3 from 'web3';

//backend addresses

export const web3 = new Web3(new Web3.providers.HttpProvider('http://cilblockchain2.uksouth.cloudapp.azure.com/api'));

export const UserRegAbi = [{"constant":true,"inputs":[{"name":"_user","type":"bytes8"},{"name":"_password","type":"bytes32"}],"name":"getLogin","outputs":[{"name":"_loginStatus","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_user","type":"bytes8"},{"name":"_password","type":"bytes32"},{"name":"_fName","type":"bytes32"},{"name":"_lName","type":"bytes32"},{"name":"_userAddress","type":"address"}],"name":"addUser","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_user","type":"bytes8"}],"name":"getWallet","outputs":[{"name":"_walletAddress","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_user","type":"bytes8"}],"name":"getUser","outputs":[{"name":"_fName","type":"bytes32"},{"name":"_lName","type":"bytes32"}],"payable":false,"type":"function"}];

export const LendCoinAbi = [{"constant":false,"inputs":[{"name":"_val","type":"uint256"},{"name":"_lendId","type":"bytes8"},{"name":"_user","type":"bytes8"}],"name":"addCoin","outputs":[{"name":"_status","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_user","type":"bytes8"}],"name":"getUserLendIds","outputs":[{"name":"","type":"bytes8[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_user","type":"bytes8"},{"name":"_lendId","type":"bytes8"}],"name":"getBalance","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_lender","type":"bytes8"},{"name":"_borrower","type":"bytes8"},{"name":"_lendId","type":"bytes8"},{"name":"_amount","type":"uint256"}],"name":"transferBalance","outputs":[{"name":"sufficient","type":"bool"}],"payable":false,"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"bytes8"},{"indexed":true,"name":"_to","type":"bytes8"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Lend","type":"event"}];

export const LenderListAbi = [{"constant":true,"inputs":[],"name":"getAllLenderList","outputs":[{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"uint256[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_user","type":"bytes8"},{"name":"_rateOfInterest","type":"uint256"},{"name":"_loanId","type":"bytes8"}],"name":"addLender","outputs":[{"name":"_success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"ListOfLoans","outputs":[{"name":"loanId","type":"bytes8"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"bytes8"}],"name":"LoanOwners","outputs":[{"name":"","type":"bytes8"}],"payable":false,"type":"function"}];

export const UserReqAbi = [{"constant":true,"inputs":[{"name":"_receiptId","type":"bytes8"}],"name":"getReceiptByReceptId","outputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"uint256"},{"name":"","type":"bytes8"},{"name":"","type":"bytes8"},{"name":"","type":"bool"},{"name":"","type":"uint16"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_receiptId","type":"bytes8"},{"name":"_loanId","type":"bytes8"},{"name":"_borrower","type":"bytes8"}],"name":"getApprovalStatusWithTS","outputs":[{"name":"_status","type":"bool"},{"name":"_ts","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"Requests","outputs":[{"name":"lendId","type":"bytes8"},{"name":"amount","type":"uint256"},{"name":"roi","type":"uint256"},{"name":"tenure","type":"uint256"},{"name":"lenderId","type":"bytes8"},{"name":"borrowerId","type":"bytes8"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_lender","type":"bytes8"},{"name":"_borrower","type":"bytes8"}],"name":"getReceiptIdsForLenderAndBorrower","outputs":[{"name":"","type":"bytes8[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_borrower","type":"bytes8"}],"name":"getReceiptIdsForBorrower","outputs":[{"name":"","type":"bytes8[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_lendId","type":"bytes8"},{"name":"_receiptId","type":"bytes8"},{"name":"_amount","type":"uint256"},{"name":"_roi","type":"uint256"},{"name":"_tenure","type":"uint256"},{"name":"_lender","type":"bytes8"},{"name":"_borrower","type":"bytes8"},{"name":"_ts","type":"uint16"}],"name":"addRequest","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_receiptId","type":"bytes8"},{"name":"_loanId","type":"bytes8"},{"name":"_borrower","type":"bytes8"},{"name":"_ts","type":"uint16"}],"name":"approaveLoanRequest","outputs":[{"name":"status","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_lender","type":"bytes8"}],"name":"getReceiptIdsForLender","outputs":[{"name":"","type":"bytes8[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_receiptId","type":"bytes8"}],"name":"getApprovalStatusWithTS","outputs":[{"name":"_status","type":"bool"}],"payable":false,"type":"function"}];

export const BorrowCoinAbi = [{"constant":false,"inputs":[{"name":"_user","type":"bytes8"},{"name":"_amount","type":"uint256"}],"name":"addBorrowerBalance","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_user","type":"bytes8"}],"name":"getBorrowerBalance","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_user","type":"bytes8"}],"name":"withdrawBalance","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"}];

export const BorrowInsAbi = [{"constant":false,"inputs":[{"name":"_amount","type":"uint256"},{"name":"_rateOfInterest","type":"uint256"},{"name":"_tenureInMonths","type":"uint256"}],"name":"calculateInstallment","outputs":[{"name":"installmentAmount","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_lender","type":"bytes8"}],"name":"getLenderInstallments","outputs":[{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"uint16[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_borrower","type":"bytes8"},{"name":"_lender","type":"bytes8"},{"name":"_loanId","type":"bytes8"},{"name":"_amount","type":"uint256"},{"name":"_tenure","type":"uint256"},{"name":"_roi","type":"uint256"},{"name":"_receiptId","type":"bytes8"},{"name":"_ts","type":"uint16"}],"name":"payInstallment","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"}];

export const AllTxAbi = [{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"AllInstallmentTxs","outputs":[{"name":"loanId","type":"bytes8"},{"name":"borrower","type":"bytes8"},{"name":"lender","type":"bytes8"},{"name":"insAmount","type":"uint256"},{"name":"ts","type":"uint16"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getInstallmentTxs","outputs":[{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"uint256[]"},{"name":"","type":"uint16[]"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_loanId","type":"bytes8"},{"name":"_borrower","type":"bytes8"},{"name":"_lender","type":"bytes8"},{"name":"_insAmount","type":"uint256"},{"name":"_ts","type":"uint16"}],"name":"addInstallmentTx","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_loanId","type":"bytes8"},{"name":"_borrower","type":"bytes8"},{"name":"_lender","type":"bytes8"},{"name":"_amount","type":"uint256"},{"name":"_roi","type":"uint256"},{"name":"_tenure","type":"uint256"},{"name":"_ts","type":"uint16"}],"name":"addLoanApproavedTxs","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"AllLoanApproaved","outputs":[{"name":"loanId","type":"bytes8"},{"name":"borrower","type":"bytes8"},{"name":"lender","type":"bytes8"},{"name":"amount","type":"uint256"},{"name":"roi","type":"uint256"},{"name":"tenure","type":"uint256"},{"name":"ts","type":"uint16"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getLoanApproavedTxs","outputs":[{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"bytes8[]"},{"name":"","type":"uint256[]"},{"name":"","type":"uint256[]"},{"name":"","type":"uint256[]"},{"name":"","type":"uint16[]"}],"payable":false,"type":"function"}];



export const UserRegAddr = '0x536455b1764ef6349729e99306c145b70c92652b'; ///0x64c8ae638d775ea82c4df14a68ab3c4ff30126a7

export const LendCoinAddr = '0x38824157f1f4addbbb94505bde013d494b9e6336';

export const LenderListAddr = '0xcd2fa22d51b9406801645f109ec9a4004cdcc3e8';

export const UserReqAddr = '0x1d9023368fc01d55388716344195705e62596b78';

export const BorrowCoinAddr = '0x18853d1c60a8057b2b33621b77155a85ceee2761';

export const BorrowInsAddr = '0x3e2dfda63abdc805200d696e9510a3e63f5ad450';

export const AllTxAddr = '0x50fcd772c55ac0ee9760ecbb293abbae3bde030c';


export const UserCon = web3.eth.contract(UserRegAbi).at(UserRegAddr);
export const LendCoinCon = web3.eth.contract(LendCoinAbi).at(LendCoinAddr);
export const LenderListCon = web3.eth.contract(LenderListAbi).at(LenderListAddr);
export const UserReqCon = web3.eth.contract(UserReqAbi).at(UserReqAddr);
export const BorrowCoinCon = web3.eth.contract(BorrowCoinAbi).at(BorrowCoinAddr);
export const BorrowInsCon = web3.eth.contract(BorrowInsAbi).at(BorrowInsAddr);
export const AllTxCon = web3.eth.contract(AllTxAbi).at(AllTxAddr);
// export const CalInsLibCon = web3.eth.contract(CalInsLibAddr).at(CalInsLibAddr);